import { app, BrowserWindow, Menu, dialog } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const TEXT_EXTENSIONS = new Set([
  '.txt', '.log', '.md', '.csv', '.json', '.xml',
  '.yaml', '.yml', '.ini', '.cfg', '.conf', '.text',
]);

let mainWindow: BrowserWindow | null = null;

const createApplicationMenu = (win: BrowserWindow): void => {
  const template: Electron.MenuItemConstructorOptions[] = [
    {
      label: 'File',
      submenu: [
        {
          label: 'Log File',
          click: async () => {
            const { canceled, filePaths } = await dialog.showOpenDialog(win, {
              title: 'Open Log File',
              buttonLabel: 'Open',
              filters: [
                {
                  name: 'Text Files',
                  extensions: ['txt', 'log', 'md', 'csv', 'json', 'xml', 'yaml', 'yml', 'ini', 'cfg', 'conf', 'text'],
                },
              ],
              properties: ['openFile'],
            });

            if (canceled) return;

            if (!filePaths || filePaths.length === 0) {
              await dialog.showMessageBox(win, {
                type: 'warning',
                title: 'No File Selected',
                message: 'No file was selected. Please select a text file to continue.',
                buttons: ['OK'],
              });
              return;
            }

            const selectedPath = filePaths[0];
            const ext = path.extname(selectedPath).toLowerCase();

            if (!TEXT_EXTENSIONS.has(ext)) {
              await dialog.showMessageBox(win, {
                type: 'warning',
                title: 'Wrong File Format',
                message: `"${path.basename(selectedPath)}" is not a supported text file.\n\nPlease select a plain text file (.txt, .log, .md, etc.).`,
                buttons: ['OK'],
              });
              return;
            }

            try {
              const content = fs.readFileSync(selectedPath, 'utf-8');
              win.webContents.send('log-file-loaded', {
                content,
                filePath: selectedPath,
                fileName: path.basename(selectedPath),
              });
            } catch (err) {
              await dialog.showMessageBox(win, {
                type: 'error',
                title: 'Error Reading File',
                message: `Could not read "${path.basename(selectedPath)}".\n\n${(err as Error).message}`,
                buttons: ['OK'],
              });
            }
          },
        },
        { type: 'separator' },
        { role: 'quit' },
      ],
    },
    { role: 'editMenu' },
    { role: 'viewMenu' },
    { role: 'windowMenu' },
    { label: 'Help', submenu: [{ role: 'about' }] },
  ];

  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
};

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  createApplicationMenu(mainWindow);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
